version: '2'
services:
  web:
    build: .
    command: yarn test
    volumes:
      - .:/usr/app/
      # - /usr/app/node_modules
    # ports:
    #   - "3005:3000"
    #   - "5985:5984"
    depends_on:
      - couch
    environment:
      COUCH_URL: http://localhost:5984
  couch:
    image: couchdb:2.1.1
    ports:
      - "5984"
    environment:
      COUCHDB_NAME: couch-test
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
