version: '2'
services:
  test:
    build: .
    command: yarn test
    volumes:
      - .:/usr/app/
      # - /usr/app/node_modules
    # ports:
    #   - "3005:3000"
    #   - "5985:5984"
    # depends_on:
    #   - couch
    links:
      - couch
      - postgres
    environment:
      COUCH_URL: http://localhost:5984
  couch:
    image: couchdb:2
    ports:
      - "5984"
    environment:
      COUCHDB_NAME: couch-test
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
  postgres:
    image: postgres:9
    ports:
      - "5432"
